apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-docs
  description: testing docs template
  annotations:
    github.com/project-slug: boss-test/docs-test
    backstage.io/techdocs-ref: github:https://github.com/boss-test/docs-test
spec:
  type: documentation
  lifecycle: experimental
  owner: Rugvip
